#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri Jan 02 06:33:44 QYZT 2026
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryShaders_v4.6
