#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Mon Jan 19 17:16:47 QYZT 2026
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryShaders_v4.6
