#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sat Dec 27 22:12:46 QYZT 2025
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryShaders_v4.6
